import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/provider/convex-client-provider";
import { Toaster } from "sonner";

const inter = Comic_Neue({ weight: ["300", "400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
      <ConvexClientProvider>
        <Toaster/>
          {children}
      </ConvexClientProvider>
          </body>
    </html>
  );
}
